version: '3'

services:
  sctp_sender:
    build:
      context: .
      dockerfile: ./e2app/Dockerfile.sender
    networks:
      - sctp_network

  sctp_receiver:
    build:
      context: .
      dockerfile: ./e2app/Dockerfile.receiver
    networks:
      - sctp_network

networks:
  sctp_network:
    driver: bridge
