version: '3.8'
services:
  web:
    build: .
    ports:
      - "4000:80"
    environment:
      - NAME=World
    command: ["python", "app.py"]  # Specify the command to run the application
    restart: always
